spring:
  application:
    name: tigetting

  datasource:
    url: jdbc:mysql://localhost:3306/tigetting?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: tigetting
    password: tigetting
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.ssafy.tigetting.mapper
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: ${JWT_SECRET:THIS_IS_A_LONG_RANDOM_PLAIN_SECRET_WITH_32+_CHARS_1234567890abcdef}
  access-token-validity-ms: 3600000